export const STORE_SEARCH_RESULT = "STORE_SEARCH_RESULT";
export const STORE_SEARCH_QUERY = "STORE_SEARCH_QUERY";
export const STORE_CATEGORIES_LIST = "STORE_CATEGORIES_LIST";
export const ADD_TO_CART = "ADD_TO_CART";
export const STORE_CART_LIST = "STORE_CART_LIST";
export const STORE_PROFILE_INFO = "STORE_PROFILE_INFO";
export const STORE_COURSE_DETAILS = "STORE_COURSE_DETAILS"